.\" Process this file with
.\" groff -man -Tascii gwibber.1
.\"
.TH GWIBBER 1 "FEBRUARY 2009" Linux "User Manuals"
.SH NAME
Gwibber \- Microblogging client for GNOME
.SH SYNOPSIS
.B gwibber [
.I OPTIONS
.B ]
.SH DESCRIPTION
.B Gwibber
is an open source microblogging client for GNOME developed with Python and GTK. It supports Twitter, Jaiku, Identi.ca, Facebook, Flickr, Digg, and RSS.
.SH OPTIONS
.IP "-h, --help"
Show help message and exit
.IP "-v, --verbose"
Verbose messages
.IP "-d, --debug"
Debug messages
.SH BUGS
Please report all bugs to the Gwibber bug tracker:
http://launchpad.net/gwibber
.SH AUTHOR
Greg Grossmeier <greg@grossmeier.net>

Copyright 2009.  Licensed under a Creative Commons Attribution-ShareAlike License <http://creativecommons.org/licenses/by-sa/3.0/>
